name: ClickableHolosTest
main: eu.virtusdevelops.clickableholostest.ClickableHolosTest
version: "TEST"


commands:
  simpleholograms:
    description: "Main command"
    permission: "simpleholograms.command.main"